### ISSUE TITLE
Not able to get any data from OSM dataframe

### ISSUE THREAD

**Issue by durgeshNdas-90** [akashihi/spark-osm-datasource#1]
After creating a dataframe for OSM data using com.wolt.osm.spark.OsmSource ,  i'm only receiving schema information. however not able to get any data from the dataframe. 
import com.wolt.osm.spark.OsmSource
spark.sparkContext.addFile("/dbfs/mnt/raw/external/osm/building/2020/08/26/japan-latest.osm.pbf")
val entityDF = spark.read.option("partitions", 128).option("useLocalFile", "true").format("com.wolt.osm.spark.OsmSource").load("japan-latest.osm.pbf").drop("INFO")
entityDF.createOrReplaceTempView("osm_entities")

![image](https://user-images.githubusercontent.com/70638064/91972621-97dcc180-ed38-11ea-8c33-83bb85a9d2ce.png)

**Comment by akashihi** [comment]
I just checked it on my system - should work. Could you please try to simplify your code and check what will happen? Something like:
```
spark.sparkContext.addFile("/dbfs/mnt/raw/external/osm/building/2020/08/26/japan-latest.osm.pbf")
val entityDF = spark.read.option("partitions", 128).option("useLocalFile", "true").format("com.wolt.osm.spark.OsmSource").load("japan-latest.osm.pbf")
entityDF.show(false)
```

**Comment by akashihi** [comment]
Closing as 1 have no feedback in ~1 year
